Vagrant.configure("2") do |config|
    # monitor machine with nagios installed
    config.vm.define "monitor"  do |monitor|
        monitor.vm.hostname = "monitor"
        monitor.vm.box = "starboard/ubuntu-arm64-20.04.5"
        monitor.vm.box_version = "20221120.20.40.0"
        monitor.vm.box_download_insecure = true
        monitor.vm.provider "vmware_desktop"  do |v|
            v.ssh_info_public = true #Allowing to get information of the virtual machine SSH key
            v.gui = true #In Mac computer with Apple Silicon processors we need to have GUI enabled otherwise it doesn't work.
            v.linked_clone = false
            v.vmx["ethernet0.virtualdev"] = "vmxnet3" #Hypervisor network driver that is optimized to provide high performance, high throughput, and minimal latency
        end
        monitor.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php
        cd /tmp
        #commands to install sendEmail
        wget http://caspian.dotconf.net/menu/Software/SendEmail/sendEmail-v1.56.tar.gz
        tar xzf sendEmail-v1.56.tar.gz
        sudo cp -a sendEmail-v1.56/sendEmail /usr/local/bin
        sudo chmod +x /usr/local/bin/sendEmail
        #commands to install nagios on the machine
        wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.6.tar.gz
        tar xzf nagioscore.tar.gz
        cd nagioscore-nagios-4.4.6/
        sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
        sudo make all
        sudo useradd nagios
        sudo usermod -a -G nagios www-data
        sudo make install
        sudo make install-init
        sudo make install-config
        sudo make install-commandmode
        sudo make install-daemoninit
        sudo make install-webconf
        sudo a2enmod rewrite
        sudo a2enmod cgi
        sudo ufw allow Apache
        sudo ufw reload
        #Creating a nagios user
        sudo htpasswd -c -b /usr/local/nagios/etc/htpasswd.users nagiosadmin nagiosadmin
        #Restarting nagios to apply the changes
        sudo systemctl restart apache2.service
        sudo systemctl start nagios.service
        # Installing plugins
        sudo apt-get install -y autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext iputils-ping
        cd /tmp
        wget --no-check-certificate -O nagios-plugins.tar.gz https://github.com/nagios-plugins/nagios-plugins/archive/release-2.3.3.tar.gz
        tar xzf nagios-plugins.tar.gz
        cd nagios-plugins-release-2.3.3/
        sudo ./tools/setup
        sudo ./configure
        sudo make
        sudo make install
        #NRPE plugin
        cd /tmp/
        wget https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-4.0.2/nrpe-4.0.2.tar.gz
        tar xzf nrpe-4.0.2.tar.gz
        cd /tmp/nrpe-4.0.2/
        sudo ./configure --enable-command-args --with-ssl-lib=/usr/lib/aarch64-linux-gnu/
        sudo make check_nrpe
        sudo make install-plugin
        #Restarting nagios again to apply changes
        sudo systemctl restart nagios.service
        SHELL
        # Redirect port http 80 to 8080 on host to access nagios web interface
        monitor.vm.network "forwarded_port", guest: 80, host: 8080
        # Share config file of nagios to host machine | config.vm.synced_folder "host dir", "VM dir"
        monitor.vm.synced_folder "monitor/nagios/etc", "/usr/local/nagios/etc"
    end
    config.vm.define "server"  do |server|
        server.vm.hostname = "server"
        server.vm.box = "starboard/ubuntu-arm64-20.04.5"
        server.vm.box_version = "20221120.20.40.0"
        server.vm.box_download_insecure = true
        server.vm.provider "vmware_desktop"  do |v|
            v.ssh_info_public = true #Allowing to get information of the virtual machine SSH key
            v.gui = true #In Mac computer with Apple Silicon processors we need to have GUI enabled otherwise it doesn't work.
            v.linked_clone = false
            v.vmx["ethernet0.virtualdev"] = "vmxnet3" #Hypervisor network driver that is optimized to provide high performance, high throughput, and minimal latency
        end
        #commands to install nagios on the machine
        server.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get -y install tomcat9
            #install nrpe
            sudo apt-get install -y autoconf automake gcc libc6 libmcrypt-dev make libssl-dev wget openssl
            cd /tmp
            wget --no-check-certificate -O nrpe.tar.gz https://github.com/NagiosEnterprises/nrpe/archive/nrpe-4.1.0.tar.gz
            tar xzf nrpe.tar.gz
            cd /tmp/nrpe-nrpe-4.1.0/
            sudo ./configure --enable-command-args --with-ssl-lib=/usr/lib/aarch64-linux-gnu/
            sudo make all
            sudo make install-groups-users
            sudo make install
            sudo make install-config
            sudo sh -c "echo >> /etc/services"
            sudo sh -c "sudo echo '# Nagios services' >> /etc/services"
            sudo sh -c "sudo echo 'nrpe    5666/tcp' >> /etc/services"
            sudo make install-init
            sudo systemctl enable nrpe.service
            sudo apt-get install -y ufw
            sudo mkdir -p /etc/ufw/applications.d
            sudo sh -c "echo '[NRPE]' > /etc/ufw/applications.d/nagios"
            sudo sh -c "echo 'title=Nagios Remote Plugin Executor' >> /etc/ufw/applications.d/nagios"
            sudo sh -c "echo 'description=Allows remote execution of Nagios plugins' >> /etc/ufw/applications.d/nagios"
            sudo sh -c "echo 'ports=5666/tcp' >> /etc/ufw/applications.d/nagios"
            sudo ufw allow NRPE
            sudo ufw reload
            #sudo sh -c "sed -i '/^allowed_hosts=/s/$/,192.168.64.177/' /usr/local/nagios/etc/nrpe.cfg"
            sudo sh -c "sed -i 's/^dont_blame_nrpe=.*/dont_blame_nrpe=1/g' /usr/local/nagios/etc/nrpe.cfg"
            sudo systemctl start nrpe.service
            sudo apt-get install -y autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext
            cd /tmp
            wget --no-check-certificate -O nagios-plugins.tar.gz https://github.com/nagios-plugins/nagios-plugins/archive/release-2.2.1.tar.gz
            tar zxf nagios-plugins.tar.gz
            cd /tmp/nagios-plugins-release-2.2.1/
            sudo ./tools/setup
            sudo ./configure --build=aarch64-unknown-linux-gnu
            sudo make
            sudo make install
        SHELL
        server.vm.synced_folder "server/nagios/etc", "/usr/local/nagios/etc"
    end
end
